### ISSUE TITLE
app doesn't boot

### ISSUE THREAD

**Issue by cdaringe** [thomaspeklak/node-wiki#49]
1. nodemon dependency needs to be part of the install docs
1. default boot renders following error:

```js
21 Jan 11:10:56 - [nodemon] v1.3.2
21 Jan 11:10:56 - [nodemon] to restart at any time, enter `rs`
21 Jan 11:10:56 - [nodemon] watching: /Users/cdieringer/node/node-wiki/lib/**/* /Users/cdieringer/node/node-wiki/models/**/* /Users/cdieringer/node/node-wiki/routes/**/*
21 Jan 11:10:56 - [nodemon] starting `node .`
Live reload watching public dir
watching frontend for changes
Express server listening on port 3000
Could not connect to database "mongodb://localhost/nodewiki". Ensure that a mongo db instance is up and running.
[Error: failed to connect to [localhost:27017]]
21 Jan 11:10:57 - [nodemon] app crashed - waiting for file changes before starting...

net.js:614
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:614:11)
    at finder.deleted (/Users/cdieringer/node/node-wiki/lib/wipe-deleted-pages.js:11:24)
    at NativeConnection.Connection.error (/Users/cdieringer/node/node-wiki/node_modules/mongoose/lib/connection.js:381:24)
    at /Users/cdieringer/node/node-wiki/node_modules/mongoose/lib/connection.js:409:14
    at /Users/cdieringer/node/node-wiki/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:56:21
    at /Users/cdieringer/node/node-wiki/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:267:16
    at null.<anonymous> (/Users/cdieringer/node/node-wiki/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:550:7)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/cdieringer/node/node-wiki/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at emit (events.js:98:17)
```

**Comment by thomaspeklak** [comment]
1) true, should be a dev dependency
2) the error suggests that you do not have a mongodb running or correctly configured
